[theme]
theme = "srcery"
[icons]
icons = "awesome6"

[[block]]
block = "temperature"
 
[[block]]
block = "music"
max_width = 21
marquee = false
player = "spotify"
buttons = ["play", "next"]
 
[[block]]
block = "load"
interval = 1
format = "{1m} {5m} {15m}"
 
[[block]]
block = "cpu"
interval = 0.7
 
[[block]]
block = "memory"
interval = 5
info_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"
 
[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
 
[[block]]
block = "disk_space"
path = "/home/tl"
alias = "~"
info_type = "available"
unit = "GB"
interval = 20
 
[[block]]
block = "battery"
device = 0
 
[[block]]
block = "sound"
 
[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
